
application: gae-python-boilerplate
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: off

libraries:
- name: webapp2
  version: latest

handlers:
- url: /signup
  script: authentication.app
  secure: always

- url: /login
  script: authentication.app
  secure: always

- url: /forgot
  script: authentication.app
  secure: always

- url: /.*
  script: main.app